//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickParameters.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickParameters.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade Expert.
        /// </summary>
        internal static string BladeExpert {
            get {
                return ResourceManager.GetString("BladeExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Mill.
        /// </summary>
        internal static string CircleMill {
            get {
                return ResourceManager.GetString("CircleMill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour.
        /// </summary>
        internal static string Contour {
            get {
                return ResourceManager.GetString("Contour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to 5-axis.
        /// </summary>
        internal static string ConvertTo5Axis {
            get {
                return ResourceManager.GetString("ConvertTo5Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood.
        /// </summary>
        internal static string CoolantFlood {
            get {
                return ResourceManager.GetString("CoolantFlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolant.
        /// </summary>
        internal static string CoolantLabel {
            get {
                return ResourceManager.GetString("CoolantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mist.
        /// </summary>
        internal static string CoolantMist {
            get {
                return ResourceManager.GetString("CoolantMist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string CoolantOff {
            get {
                return ResourceManager.GetString("CoolantOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string CoolantOn {
            get {
                return ResourceManager.GetString("CoolantOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thru-Tool.
        /// </summary>
        internal static string CoolantThruTool {
            get {
                return ResourceManager.GetString("CoolantThruTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coons.
        /// </summary>
        internal static string Coons {
            get {
                return ResourceManager.GetString("Coons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deburr.
        /// </summary>
        internal static string Deburr {
            get {
                return ResourceManager.GetString("Deburr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drilling.
        /// </summary>
        internal static string Drill {
            get {
                return ResourceManager.GetString("Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraving.
        /// </summary>
        internal static string Engraving {
            get {
                return ResourceManager.GetString("Engraving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facing.
        /// </summary>
        internal static string Facing {
            get {
                return ResourceManager.GetString("Facing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBM Drill Control Operation.
        /// </summary>
        internal static string FBMDrillControlOperation {
            get {
                return ResourceManager.GetString("FBMDrillControlOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBM Mill Contour Operation.
        /// </summary>
        internal static string FBMMillContourOperation {
            get {
                return ResourceManager.GetString("FBMMillContourOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBM Mill Pocket Operation.
        /// </summary>
        internal static string FBMMillPocketOperation {
            get {
                return ResourceManager.GetString("FBMMillPocketOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedrate.
        /// </summary>
        internal static string FeedRateLabel {
            get {
                return ResourceManager.GetString("FeedRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-axis Circle.
        /// </summary>
        internal static string FiveAxisCircle {
            get {
                return ResourceManager.GetString("FiveAxisCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helix Bore.
        /// </summary>
        internal static string HelixBore {
            get {
                return ResourceManager.GetString("HelixBore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters.
        /// </summary>
        internal static string Letters {
            get {
                return ResourceManager.GetString("Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lofted.
        /// </summary>
        internal static string Lofted {
            get {
                return ResourceManager.GetString("Lofted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Entry.
        /// </summary>
        internal static string ManualEntry {
            get {
                return ResourceManager.GetString("ManualEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Chamfer.
        /// </summary>
        internal static string ModelChamfer {
            get {
                return ResourceManager.GetString("ModelChamfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Curve.
        /// </summary>
        internal static string MultiaxisCurve {
            get {
                return ResourceManager.GetString("MultiaxisCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Drill.
        /// </summary>
        internal static string MultiaxisDrill {
            get {
                return ResourceManager.GetString("MultiaxisDrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Link.
        /// </summary>
        internal static string MultiaxisLink {
            get {
                return ResourceManager.GetString("MultiaxisLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Morph.
        /// </summary>
        internal static string MultiaxisMorph {
            get {
                return ResourceManager.GetString("MultiaxisMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Parallel.
        /// </summary>
        internal static string MultiaxisParallel {
            get {
                return ResourceManager.GetString("MultiaxisParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Project.
        /// </summary>
        internal static string MultiaxisProject {
            get {
                return ResourceManager.GetString("MultiaxisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Roughing.
        /// </summary>
        internal static string MultiaxisRoughing {
            get {
                return ResourceManager.GetString("MultiaxisRoughing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis SWARF.
        /// </summary>
        internal static string MultiaxisSWARF {
            get {
                return ResourceManager.GetString("MultiaxisSWARF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiaxis Triangular Mesh.
        /// </summary>
        internal static string MultiaxisTriangularMesh {
            get {
                return ResourceManager.GetString("MultiaxisTriangularMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multisurface Rough Pocket.
        /// </summary>
        internal static string MultisurfaceRoughPocket {
            get {
                return ResourceManager.GetString("MultisurfaceRoughPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onionskin Nesting.
        /// </summary>
        internal static string OnionskinNesting {
            get {
                return ResourceManager.GetString("OnionskinNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket.
        /// </summary>
        internal static string Pocket {
            get {
                return ResourceManager.GetString("Pocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port 5-axis.
        /// </summary>
        internal static string Port5Axis {
            get {
                return ResourceManager.GetString("Port5Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Expert.
        /// </summary>
        internal static string PortExpert {
            get {
                return ResourceManager.GetString("PortExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Cycle Command Block.
        /// </summary>
        internal static string ProbeCycleCommandBlock {
            get {
                return ResourceManager.GetString("ProbeCycleCommandBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Cycle Header.
        /// </summary>
        internal static string ProbeCycleHeader {
            get {
                return ResourceManager.GetString("ProbeCycleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Cycle Probe Motion.
        /// </summary>
        internal static string ProbeCycleProbeMotion {
            get {
                return ResourceManager.GetString("ProbeCycleProbeMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe Cycle Trailer.
        /// </summary>
        internal static string ProbeCycleTrailer {
            get {
                return ResourceManager.GetString("ProbeCycleTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolved.
        /// </summary>
        internal static string Revolved {
            get {
                return ResourceManager.GetString("Revolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotary Advanced.
        /// </summary>
        internal static string RotaryAdvanced {
            get {
                return ResourceManager.GetString("RotaryAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruled.
        /// </summary>
        internal static string Ruled {
            get {
                return ResourceManager.GetString("Ruled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saw.
        /// </summary>
        internal static string Saw {
            get {
                return ResourceManager.GetString("Saw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice 5-axis.
        /// </summary>
        internal static string Slice5Axis {
            get {
                return ResourceManager.GetString("Slice5Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Milling.
        /// </summary>
        internal static string SlotMilling {
            get {
                return ResourceManager.GetString("SlotMilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Model Operation.
        /// </summary>
        internal static string SolidModelOperation {
            get {
                return ResourceManager.GetString("SolidModelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle Speed.
        /// </summary>
        internal static string SpindleSpeedLabel {
            get {
                return ResourceManager.GetString("SpindleSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish Contour.
        /// </summary>
        internal static string SurfaceFinishContour {
            get {
                return ResourceManager.GetString("SurfaceFinishContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish Flowline.
        /// </summary>
        internal static string SurfaceFinishFlowline {
            get {
                return ResourceManager.GetString("SurfaceFinishFlowline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish Parallel.
        /// </summary>
        internal static string SurfaceFinishParallel {
            get {
                return ResourceManager.GetString("SurfaceFinishParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish Project.
        /// </summary>
        internal static string SurfaceFinishProject {
            get {
                return ResourceManager.GetString("SurfaceFinishProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish Radial.
        /// </summary>
        internal static string SurfaceFinishRadial {
            get {
                return ResourceManager.GetString("SurfaceFinishRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface High Speed.
        /// </summary>
        internal static string SurfaceHighSpeed {
            get {
                return ResourceManager.GetString("SurfaceHighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Rough Contour.
        /// </summary>
        internal static string SurfaceRoughContour {
            get {
                return ResourceManager.GetString("SurfaceRoughContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Rough Flowline.
        /// </summary>
        internal static string SurfaceRoughFlowline {
            get {
                return ResourceManager.GetString("SurfaceRoughFlowline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Rough Parallel.
        /// </summary>
        internal static string SurfaceRoughParallel {
            get {
                return ResourceManager.GetString("SurfaceRoughParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Rough Plunge.
        /// </summary>
        internal static string SurfaceRoughPlunge {
            get {
                return ResourceManager.GetString("SurfaceRoughPlunge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Rough Pocket.
        /// </summary>
        internal static string SurfaceRoughPocket {
            get {
                return ResourceManager.GetString("SurfaceRoughPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Rough Project.
        /// </summary>
        internal static string SurfaceRoughProject {
            get {
                return ResourceManager.GetString("SurfaceRoughProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Rough Radial.
        /// </summary>
        internal static string SurfaceRoughRadial {
            get {
                return ResourceManager.GetString("SurfaceRoughRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept 2D.
        /// </summary>
        internal static string Swept2D {
            get {
                return ResourceManager.GetString("Swept2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept 3D.
        /// </summary>
        internal static string Swept3D {
            get {
                return ResourceManager.GetString("Swept3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Cutoff.
        /// </summary>
        internal static string TabCutoff {
            get {
                return ResourceManager.GetString("TabCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Mill.
        /// </summary>
        internal static string ThreadMill {
            get {
                return ResourceManager.GetString("ThreadMill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Diameter.
        /// </summary>
        internal static string ToolDiameterLabel {
            get {
                return ResourceManager.GetString("ToolDiameterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Name.
        /// </summary>
        internal static string ToolNameLabel {
            get {
                return ResourceManager.GetString("ToolNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Number.
        /// </summary>
        internal static string ToolNumberLabel {
            get {
                return ResourceManager.GetString("ToolNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Plane.
        /// </summary>
        internal static string ToolPlaneLabel {
            get {
                return ResourceManager.GetString("ToolPlaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        internal static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmed.
        /// </summary>
        internal static string Trimmed {
            get {
                return ResourceManager.GetString("Trimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D High Speed.
        /// </summary>
        internal static string TwoDHighSpeed {
            get {
                return ResourceManager.GetString("TwoDHighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Offset.
        /// </summary>
        internal static string WorkOffsetLabel {
            get {
                return ResourceManager.GetString("WorkOffsetLabel", resourceCulture);
            }
        }
    }
}
